name: Clean old GitHub Pages Deployments

on:
  workflow_dispatch:  # execute manually

permissions:
  contents: write
  deployments: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete old GitHub Pages deployments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEEP: 3   # number of last deployments to keep
        run: |
          echo "Fetching all deployments..."
          DEPLOYMENTS=$(gh api -H "Accept: application/vnd.github+json" \
            /repos/${GITHUB_REPOSITORY}/deployments --paginate)
          
          # filter deployment IDs: only github-pages, exclude releases
          IDS=$(echo "$DEPLOYMENTS" | jq -r '.[] | select(.environment=="github-pages") | .id')

          COUNT=$(echo "$IDS" | wc -l)
          echo "Total GitHub Pages deployments: $COUNT"

          # delete old deployments, only keep $KEEP 
          TO_DELETE=$(echo "$IDS" | head -n -$KEEP)

          for id in $TO_DELETE; do
            echo "Deleting deployment ID $id"
            gh api -X DELETE /repos/${GITHUB_REPOSITORY}/deployments/$id
          done
