name: Clean old GitHub Pages Deployments

on:
  workflow_dispatch:  # execute manually

permissions:
  contents: write
  deployments: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Delete inactive GitHub Pages deployments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Fetching all deployments..."
          DEPLOYMENTS=$(gh api -H "Accept: application/vnd.github+json" \
            /repos/${GITHUB_REPOSITORY}/deployments --paginate)

          # filter deployment IDs: only github-pages with status not active
          IDS=$(echo "$DEPLOYMENTS" | jq -r '.[] | select(.environment=="github-pages" and .status!="active") | .id')

          COUNT=$(echo "$IDS" | wc -l)
          echo "Total inactive GitHub Pages deployments: $COUNT"

          if [ "$COUNT" -eq 0 ]; then
            echo "No inactive deployments to delete."
            exit 0
          fi

          for id in $IDS; do
            echo "Deleting deployment ID $id"
            gh api -X DELETE /repos/${GITHUB_REPOSITORY}/deployments/$id
          done
