name: coverage

on: [push, pull_request]

jobs:
  codacy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest pytest-cov codacy-coverage

      - name: Run tests with coverage
        run: pytest --cov=snib --cov-report=xml --cov-report=term-missing || true

      - name: Upload coverage to Codacy
        env:
            CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
            CODACY_ORGANIZATION_PROVIDER: gh
            CODACY_USERNAME: patmllr
            CODACY_PROJECT_NAME: snib
        run: python-codacy-coverage -r coverage.xml -c ${{ github.sha }}
